#spring.datasource.url=jdbc:postgresql://localhost:5432/bankproject
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bankproject
